### PR TITLE
Network synced registries

### LINKED ISSUE #803: Can't join the game 1.20.6 from Velocity
**Describe the bug**
I can't join my server because of a packet event error.

**Software brand**
Paper 1.20.6 version 120 (last stable version)

**Plugins**
Please give us a list of your plugins. Sometimes we run into incompatibilities. Having an overview of the plugins on your server can really help identify the problem quicker.
Eg. ViaVersion, ProtocolLib, HolographicDisplays
You may also provide a screenshot.

**How To Reproduce**
*Example:*
1. Configure a velocity proxy.
2. Configure an 1.20.6 lobby server without packetevents
3. Configure an other 1.20.6 server with packetevents
4. Try to join lobby then the other server.

**Expected behavior**
Be able to join the server

**Screenshots**
```java
[11:36:26 INFO]: Hydrolien joined the game
[11:36:26 INFO]: Hydrolien[/192.168.1.115:48780] logged in with entity id 4 at ([rome]307.966863292356, 66.5, -407.17930461665327)
[11:36:28 INFO]: Hydrolien lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
[11:36:28 INFO]: Hydrolien left the game
```

I use packetevents as a dependency for AntiHealthIndicator.

### LINKED ISSUE #849: Entity is "null"
**Describe the bug**
It kicks everyone and makes the server not joinable as soon as you spawn an entity let's say: zombie.

**Software brand**
Pufferfish 1.19.4

**Plugins**
ViaVersion, ProtocolLib, Matrix, Libs Disguises, MythicMobs, and alot more.

**How To Reproduce**
*Example:*
1. I'm on 1.20.1 
2. Spawn zombie with command or egg
3. And boom, you're kicked and can't join until the zombie dies

*It's fine with the old version: 2.2.1*, entity is "null"

### LINKED ISSUE #850: Use 1.21 datapack in 1.20.6 server causes error/kick
**Describe the bug**
```
[01:25:42 WARN]: io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
[01:25:42 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at ProtocolLib (14).jar//com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[01:25:42 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[01:25:42 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[01:25:42 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[01:25:42 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[01:25:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[01:25:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[01:25:42 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[01:25:42 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[01:25:42 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[01:25:42 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[01:25:42 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[01:25:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:25:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:25:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[01:25:42 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.protocol.mapper.MappedEntity.isRegistered()" because "entity" is null
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMappedEntityOrDirect(PacketWrapper.java:1436)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.protocol.component.builtin.item.BannerLayers$Layer.write(BannerLayers.java:89)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.wrapper.PacketWrapper.writeList(PacketWrapper.java:1398)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.protocol.component.builtin.item.BannerLayers.write(BannerLayers.java:43)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.write(ComponentTypes.java:94)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:506)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:531)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientClickWindow.write(WrapperPlayClientClickWindow.java:115)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:95)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64)
[01:25:42 WARN]:        at Matrix.jar//me.rerere.matrix.thirdparty.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41)
[01:25:42 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
```

**How To Reproduce**
1. Enable 1.21 data pack in server.properties: `initial-enabled-packs=vanilla,bundle,update_1_21`
2. Regenerate the world
3. Open Loom, and use this pattern
image

* PacketEvents: 2.3.1-Snapshot
* Server: 1.20.6 Purpur

### LINKED ISSUE #861: Wolf Variant for EntityMetadata needs to be implemented (1.20.5+)
Missing implementation for WolfVariant on 1.20.5+ it seems.

### LINKED ISSUE #869: Disconnect when going near a player with an item enchanted using EcoEnchants
**Describe the bug**

Player disconnects when going near another player with an item enchanted with a custom EcoEnchants enchant.

image
`[LibsDisguises] Task #13907 for LibsDisguises v10.0.44-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentType.getId(com.github.retrooper.packetevents.protocol.player.ClientVersion)" because "enchantment" is null
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.lambda$write$1(ItemEnchantments.java:62) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeMap(PacketWrapper.java:438) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemEnchantments.write(ItemEnchantments.java:61) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.write(ComponentTypes.java:94) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStackModern(PacketWrapper.java:553) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.writeItemStack(PacketWrapper.java:578) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.write(WrapperPlayServerEntityEquipment.java:85) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:242) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.prepareForSend(PacketWrapper.java:247) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.transformWrappers(ProtocolManager.java:107) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.protocol.ProtocolManager.sendPacketSilently(ProtocolManager.java:121) ~[packetevents-spigot-2.4.0.jar:?]
        at packetevents-spigot-2.4.0.jar/com.github.retrooper.packetevents.manager.player.PlayerManager.sendPacketSilently(PlayerManager.java:53) ~[packetevents-spigot-2.4.0.jar:?]
        at LibsDisguises.jar/me.libraryaddict.disguise.utilities.packets.LibsPackets.lambda$sendDelayed$2(LibsPackets.java:86) ~[LibsDisguises.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1654) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`

**Software brand**
Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Plugins**
image
eco 6.71.3
EcoEnchants  12.10.1
packetevents 2.4.0
ProtocolLib 5.3.0-SNAPSHOT-721
LibsDisguises 10.0.44-SNAPSHOT

**How To Reproduce**
*Example:*
1. Enchant an item with a custom EcoEnchants enchantment
2. Have another play go near the player with the enchanted item in inventory
3. Disconnect 
image

**Expected behavior**
no crash?

**Screenshots**

**Additional context**
Probably not specific to ecoenchants enchants but i would imagine generally all enchants registered with the new 1.21 system.

### LINKED ISSUE #908: "enchantment" is null
**Describe the bug**
"enchantment" is null

**Software brand**
Purpur 1.21

**Plugins**
image

**How To Reproduce**
as soon as you go near an item that is enchanted (item frame etc) you are kicked off the server.
ExcellentEnchants is used, before the update to 1.21 everything ran smoothly.

**Expected behavior**
as soon as you go near an item that is enchanted (item frame etc) you are kicked off the server.
ExcellentEnchants is used, before the update to 1.21 everything ran smoothly.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by booky10**
## TODO

- [x] Implement to/from nbt encode/decoding for:
  - [x] Biomes
  - [x] Chat Types
  - [x] Trim Patterns
  - [x] Trim Materials
  - [x] Wolf Variants
  - [x] Painting Variants
  - [x] Dimension Types
  - [x] Damage Types (thanks to @libraryaddict)
  - [x] Banner Patterns
  - [x] Enchantments
  - [x] Jukebox Songs (thanks to @libraryaddict)
- [x] Migrate all synchronized registries to generic VersionedRegistry
- [x] Update dimension type handling (especially world height) and fix legacy handling
- [x] Support non-vanilla entries on registry load (load from data if available, otherwise lookup in vanilla registry)
- [x] For 1.16 to 1.20.1: Use new registries while reading packet on game join
- [x] Fix biome mappings for older versions
- [x] Reduce memory usage by only caching each registry once per "server"
  - [ ] ~~Make decoding/encoding everything optional, except for dimension types~~
- [x] Account changes in encoding/decoding across versions (@libraryaddict already did this for biomes)

## Changes

- Added new abstract registry system and migrated all network synchronized registries
- Added nbt decoding/encoding logic for all network synchronized registries
  - Enchantments were a bit more complicated, as they now also use components for storing effects
- Migrated dimension type handling from `Dimension` to new `DimensionType`
- Registries are now read in config phase or on login and re-build from sent data
  - If the server decides to not send vanilla data (or data of custom datapacks), the vanilla registry is used as a fallback
  - → When using the same custom datapack on multiple backend servers behind a proxy, this will break with this solution

## Breaking Changes

- Some `define` methods in network synchronized registries
- Dimension/world related methods (which aren't getters) no longer work in `User`

---

Fixes #908
Fixes #869 
Fixes #861 
Fixes #850 
Fixes #849 
Fixes #803

### CODE REVIEW

**Comment by re-ovo** [comment]
DimensionType.decode might cause exception on some server version
```
NBT xxx does not exist
```

Mainly `min_y`, `height`, `monsterSpawnLightLevel`, `monsterSpawnBlockLightLimit`

**Comment by booky10** [comment]
yeah there is no cross-version compat yet, I've just accounted for 1.21 logic for now
But will add that to my TODO list, thanks for the reminder!

**Comment by libraryaddict** [comment]
Were you still working on this, and are you open to pull requests to your PR?

**Comment by booky10** [comment]
> Were you still working on this, and are you open to pull requests to your PR?

If you'd like to help out, sure, I'm accepting PRs to my PR. I currently don't have much time to work on this. If you'd like to help out, ask in the packetevents discord.

**Comment by libraryaddict** [comment]
For those interested, my PR to this PR is here: https://github.com/booky10/packetevents/pull/1

**Comment by retrooper** [comment]
@libraryaddict https://github.com/libraryaddict/packetevents/pull/1

**Comment by retrooper** [comment]
image
Received this exception, hopefully it helps.

**Comment by booky10** [comment]
which minecraft version?

**Comment by retrooper** [comment]
> which minecraft version?

Paper 1.21

**Comment by libraryaddict** [comment]
>  Reduce memory usage by only caching each registry once per "server" 

What happens if a plugin decides to add a new registry entry that isn't shared by all players on a server? Would that be explicitly unsupported?

**Comment by booky10** [comment]
With caching enabled, yes

File: api/src/main/java/com/github/retrooper/packetevents/manager/InternalPacketListener.java [hunk 1]
```diff
@@ -88,7 +88,7 @@ else if (event.getPacketType() == PacketType.Configuration.Server.REGISTRY_DATA)
 
             if (packet.getElements() != null) { // 1.20.2 to 1.20.5
                 SynchronizedRegistriesHandler.handleRegistry(user, packet.getServerVersion().toClientVersion(),
-                        packet.getRegistryKey(), packet.getElements());
+                        packet.getRegistryKey(), packet.getElements(), !PacketEvents.getAPI().getInjector().isProxy());
```
Comment (retrooper) [inline api/src/main/java/com/github/retrooper/packetevents/manager/InternalPacketListener.java]: Here we check if we are running on proxy.
If not, we cache the registries globally to save memory.

File: api/src/main/java/com/github/retrooper/packetevents/util/mappings/SynchronizedRegistriesHandler.java [hunk 2]
```diff
@@ -80,12 +81,32 @@ private SynchronizedRegistriesHandler() {
...
+
+                    //Did we already cache these? If so, skip...
+                    if (versionedRegistry.getSynchronizedRegistry() != null) return;
+
+                    versionedRegistry.synchronizeRegistry(syncedRegistry);
+                }
+
+                // Dimension type registry is the one exception that we always store for each user.
+                if (syncedRegistry.getRegistryKey().equals(DimensionTypes.getRegistry().getRegistryKey())) {
+                    user.putUserRegistry(syncedRegistry);
```
Comment (retrooper) [inline api/src/main/java/com/github/retrooper/packetevents/util/mappings/SynchronizedRegistriesHandler.java]: If we are on proxy, we store all registries for each user.
If we are not on proxy, we only store the dimension type registry for each user, and cache everything else.

File: api/src/main/java/com/github/retrooper/packetevents/util/mappings/VersionedRegistry.java [hunk 3]
```diff
@@ -38,6 +38,10 @@ public final class VersionedRegistry<T extends MappedEntity> implements IRegistr
     private final Map<String, T> typeMap = new HashMap<>();
     private final Map<Byte, Map<Integer, T>> typeIdMap = new HashMap<>();
 
+    //Each version registry may have a synchronized registry cache, for convenience and enhanced performance.
+    @Nullable
+    private SimpleRegistry<T> synchedRegistry = null;
```
Comment (retrooper) [inline api/src/main/java/com/github/retrooper/packetevents/util/mappings/VersionedRegistry.java]: If this cache registry within the VersionedRegistry is available, (not null) then it will be used.

**Comment by retrooper** [comment]
Howcome the handleRegistriesLegacy method contains "legacy" but is used on 1.21 again? Perhaps we can change that to avoid confusion unless its intentional.

**Comment by retrooper** [comment]
The very last commit is untested, noticed that I forgot the legacy registries.

**Review by retrooper — APPROVED** [review]
Looks good. Will be included in 2.5.0-SNAPSHOT for users to conveniently test until the release.

**Comment by retrooper** [comment]
Thanks for the PR @booky10 and @libraryaddict!
