### PR TITLE
fix: NPC objects to have unique server team names.

### LINKED ISSUE #1040: All NPC objects share same unique scoreboard team name.
**Describe the bug**
All instances of the NPC class share the same scoreboard team name, which, in effect, means all NPC's share the same metadata of that team. (prefix/suffix). 

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L439

**Software brand**
Please let us know what software you are using.
Paper version 1.21.1-105-master@b7ab22d (2024-09-27T18:16:58Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Expected behavior**
Instances of NPCs should have unique and independent team names.

**Screenshots**
Screenshot 2024-10-24 at 9 10 45 pm
Screenshot 2024-10-24 at 9 10 51 pm
Screenshot 2024-10-24 at 9 11 12 pm

### PR DESCRIPTION
**Pull request by ShreyasAyyengar**
Fixes #1040

@retrooper!

### CODE REVIEW

**Comment by booky10** [comment]
Could you create a private field (type String) which defaults to this string for the teamname, plus a getter/setter?
That way you can decide wether to share prefixes/suffixes or not on your own, instead of being forced

**Comment by ShreyasAyyengar** [comment]
> Could you create a private field (type String) which defaults to this string for the teamname, plus a getter/setter? That way you can decide wether to share prefixes/suffixes or not on your own, instead of being forced

Done!

**Review by booky10 — APPROVED** [review]
:+1:

**Review by booky10 — CHANGES_REQUESTED** [review]
Nevermind, this won't work
Please shorten the `teamName` to fit in the character limit of `16`

**Comment by ShreyasAyyengar** [comment]
> Nevermind, this won't work Please shorten the `teamName` to fit in the character limit of `16`

Do team names have character limits? I thought that was just the NPC's name?

**Comment by booky10** [comment]
The team name limit was removed in 1.18, versions before that have a team name limit of 16

**Comment by ShreyasAyyengar** [comment]
> The team name limit was removed in 1.18, versions before that have a team name limit of 16

I see. I've just committed to this fix; let me know if it's appropriate.

**Comment by booky10** [comment]
This won't solve the problem - the default team name will always consist of at least 18 characters

**Comment by ShreyasAyyengar** [comment]
Would it be appropriate if the team name was simplified to just the entityId? Or perhaps `team-{id}`

**Comment by booky10** [comment]
`npc_<id>` or so, yeah - it doesn't need to be complicated

**Review by booky10 — APPROVED** [review]

File: api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java [hunk 1]
```diff
@@ -410,6 +412,16 @@ public void setSuffixName(@Nullable Component nameSuffix) {
         this.suffixName = nameSuffix;
     }
 
+    public String getTeamName() {
+        return teamName;
+    }
+
+    public void setTeamName(String teamName) {
+        if (PacketEvents.getAPI().getServerManager().getVersion().isOlderThan(ServerVersion.V_1_18)) {
```
Comment (retrooper) [inline api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java:420]: Use
```java
serverVersion.isOlderThan(ServerVersion.V_1_18)
``` 
instead of accessing the global server version.

**Review by retrooper — CHANGES_REQUESTED** [review]

File: api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java (hunk 1 above)
Comment (ShreyasAyyengar) [reply api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java:420]: Not quite sure what you mean here. I've written the check similarly to many other version-checking condition checks.

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L260

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L249

https://github.com/retrooper/packetevents/blob/d8a44fe8b6143578afd969c1eb192d782377e2b5/api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java#L233

Comment (retrooper) [reply api/src/main/java/com/github/retrooper/packetevents/protocol/npc/NPC.java:420]: There's a variable within PacketWrapper, I'm saying use it.

**Comment by retrooper** [comment]
Thanks for the PR.
