### PR TITLE
Ensure dimension's attributes is initialized to a non-null value

### LINKED ISSUE #483: Use of custom dimension causes NPE
See title. Using a shaded `2.0.0-SNAPSHOT` Stacktrace is as follows:
```
Caused by: java.lang.NullPointerException
        at <internal package>.packetevents.protocol.world.Dimension.getDimensionName(Dimension.java:39) ~[?:?]
        at <internal package>.packetevents.wrapper.PacketWrapper.writeDimension(PacketWrapper.java:717) ~[?:?]
        at <internal package>.packetevents.wrapper.play.server.WrapperPlayServerRespawn.write(WrapperPlayServerRespawn.java:115) ~[?:?]
        at <internal package>.packetevents.handlers.PacketEventsEncoder.read(PacketEventsEncoder.java:50) ~[?:?]
        at <internal package>.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:64) ~[?:?]
        at <internal package>.packetevents.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
```

Doesn't look like there's any support for dimensions specified in a datapack.

### PR DESCRIPTION
**Pull request by wordandahalf**
Fixes #483.

### CODE REVIEW

File: api/src/main/java/com/github/retrooper/packetevents/protocol/world/Dimension.java [hunk 1]
```diff
@@ -23,7 +23,7 @@
 
 public class Dimension {
     private int id;
-    private NBTCompound attributes;
+    private NBTCompound attributes = new NBTCompound();
```
Comment (NoJokeFNA) [inline api/src/main/java/com/github/retrooper/packetevents/protocol/world/Dimension.java:26]: Never do it like this, use the constructor.

**Review by NoJokeFNA — CHANGES_REQUESTED** [review]

File: api/src/main/java/com/github/retrooper/packetevents/protocol/world/Dimension.java (hunk 1 above)
Comment (Izibane) [reply api/src/main/java/com/github/retrooper/packetevents/protocol/world/Dimension.java:26]: Why may I ask?

**Comment by retrooper** [comment]
Appreciate the PR
